#codes adopted from UBC MDS DSCI 532
name: 'ds-compensation'
channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel
    - altair-all
    - dash
    - dash-bootstrap-components
    - plotly
    - r-base
    - r-tidyverse
    - r-shiny
    - r-languageserver
    - r-plotly
    - pip
pip:
    - dash-vega-components
