#codes adopted from UBC MDS DSCI 532
name: 'ds-compensation'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - ipykernel
  - dash
  - dash-bootstrap-components
  - nbformat
  - plotly
  - geopandas
  - altair-all
  - pip
  - pip:
      - dash-vega-components
      - Flask-Caching
